<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\Application\**\*.cs" Link="Application\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\..\Common\**\*.cs" Link="Common\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\..\Domain\**\*.cs" Link="Domain\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NCalcSync" Version="5.12.0" />
  </ItemGroup>
</Project>
